name: uniscape
summary: "Convert a string to its unicode representation."
website: https://github.com/sil-car/uniscape
contact: https://github.com/sil-car/uniscape/issues
issues: https://github.com/sil-car/uniscape/issues
icon: snap/gui/uniscape.svg
license: MIT
title: UniScape
description: |
  Choose the GUI app or the commandline.
adopt-info: uniscape # for version and grade
confinement: strict
# core22 migration:
#   https://forum.snapcraft.io/t/micro-howto-migrate-from-core20-to-core22/30188
base: core22
architectures:
  - amd64
  - arm64

layout:
  /usr/share/tcltk:
    symlink: $SNAP/usr/share/tcltk
environment:
  # Add site-packages/<pkg> to PYTHONPATH, otherwise module imports
  #   have to be explicit instead of relative to the project package.
  PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.10/site-packages/uniscape

apps:
  uniscape:
    command: bin/uniscape

  gui:
    command: bin/uniscape-gui
    environment:
      # https://forum.snapcraft.io/t/modulenotfounderror-no-module-named-tkinter/28707/4
      PYTHONPATH: $PYTHONPATH:$SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3.10/lib-dynload
    extensions: [gnome]

parts:
  uniscape:
    plugin: python
    source: https://github.com/sil-car/uniscape.git
    override-pull: |
      craftctl default
      snap_ver=$(grep 'version =' $CRAFT_PART_SRC/pyproject.toml | sed -r 's/^version = "(.*)"/\1/')
      craftctl set version="${snap_ver}"
      craftctl set grade="stable"
    build-packages:
      - python3-pip
    override-build: |
      # # Reinstall python to include all of Tk. (https://stackoverflow.com/a/26358646)
      # apt install --reinstall python3
      # Install dephell to convert pyproject.toml to setup.py, which is req'd. by snapcraftctl.
      # https://forum.snapcraft.io/t/building-a-core20-python-snap-using-pyproject-toml/22028/2
      pip3 install --user dephell[full]
      $HOME/.local/bin/dephell deps convert --from-path=pyproject.toml --from-format=poetry --to-path=setup.py --to-format=setuppy
      craftctl default
    stage-packages:
      - python3-tk
      - tcl8.6

  desktop-icon:
    plugin: dump
    source: snap/gui/
    organize:
      # uniscape.svg: usr/share/icons/hicolor/scalable/apps/
      # https://forum.snapcraft.io/t/detect-icon-without-altering-desktop-file/20202/6
      uniscape.svg: meta/gui/icons/hicolor/scalable/apps/snap.uniscape.svg
